---
- name: Install Servarr apps
  tags: servarr
  block:
    - name: Manage user
      user:
        name: servarr
        system: true
        home: /nonexistent
        create_home: false
        shell: /usr/sbin/nologin
        groups: "{{ servarr_user_groups }}"
      notify: Restart servarr services
    - name: Add users to group
      user:
        name: "{{ item }}"
        groups: servarr
        append: true
      with_items: "{{ servarr_group_users }}"
      notify: Restart servarr services
    - name: Install dependencies
      apt:
        name:
          - curl
          - sqlite3
          - libchromaprint-tools
          - mediainfo
        install_recommends: false
        update_cache: true
    - name: Create install directories
      file:
        state: directory
        path: "/usr/share/{{ item.key }}"
        mode: '0755'
      with_dict: "{{ servarr_apps }}"
    - name: Create data directories
      file:
        state: directory
        path: "/var/lib/{{ item.key }}"
        mode: '0775'
        owner: servarr
        group: servarr
      with_dict: "{{ servarr_apps }}"
    - name: Install packages
      unarchive:
        src: "{{ item.value.url }}"
        dest: "/usr/share/{{ item.key }}"
        remote_src: true
        owner: servarr
        group: servarr
        creates: "/usr/share/{{ item.key }}/{{ item.key | capitalize }}"
        extra_opts:
          - '--strip-components=1'
          - '--show-stored-names'
      with_dict: "{{ servarr_apps }}"
      notify: Restart servarr services
    - name: Install service file
      template:
        src: service.j2
        dest: "/etc/systemd/system/{{ item.key }}.service"
        mode: '0644'
      with_dict: "{{ servarr_apps }}"
      notify:
        - Reload systemd
        - Restart servarr services
    - name: Manage services
      service:
        name: "{{ item.key }}"
        enabled: "{{ servarr_service_enabled }}"
        state: "{{ servarr_service_state }}"
      with_dict: "{{ servarr_apps }}"
